import Navbar from "@/components/navbar";
import { Theme } from "@/theme";
import { ThemeProvider } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Auto V",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="en">
			<ThemeProvider theme={Theme}>
				<body>
					<Navbar />
					{children}
				</body>
			</ThemeProvider>
		</html>
	);
}
