import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import style from "./style.module.css";
import Footer from "@/components/footer";
import ThemeRegistry from "./ThemeRegistry";

export const metadata: Metadata = {
	title: "Auto V",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body style={{ 
				boxSizing: "border-box",
				padding: 0,
				margin: 0,
			}}>
				<ThemeRegistry options={{ key: "mui" }}>
					<header>
						<Navbar />
					</header>
					<main className={style.mainBg}>
						{children}
					</main>
					<Footer />
				</ThemeRegistry>
			</body>
		</html>
	);
}
