import Navbar from "@/components/navbar";
import { Theme } from "@/theme";
import { ThemeProvider } from "@mui/material";
import type { Metadata } from "next";
import style from "./style.module.css";
import Footer from "@/components/footer";

export const metadata: Metadata = {
	title: "Auto V",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<ThemeProvider theme={Theme}>
			<html lang="en">
				<body style={{ padding: 0, margin: 0}}>
					<header>
						<Navbar />
					</header>

					<main className={style.mainBg}>
						{children}
					</main>

					<Footer />
				</body>
			</html>
		</ThemeProvider>
	);
}
